export const allUsers = [
  {
    email: 'jonathan1@ooland.com',
    name: 'Jonathan1',
    address: 'Cloud Mansion',
    phone: 555002000,
    password: '12aaAA##',
    country: 'Space',
    city: 'Ecatepec',
  },
  {
    email: 'jonathan2@ooland.com',
    name: 'Jonathan2',
    address: 'Sky Tower',
    phone: 555002001,
    password: '12aaAA##',
    country: 'Mexico',
    city: 'Mexico City',
  },
  {
    email: 'jonathan3@ooland.com',
    name: 'Jonathan3',
    address: 'Ocean Boulevard',
    phone: 555002002,
    password: '12aaAA##',
    country: 'USA',
    city: 'Los Angeles',
  },
  {
    email: 'jonathan4@ooland.com',
    name: 'Jonathan4',
    address: 'Mountain View',
    phone: 555002003,
    password: '12aaAA##',
    country: 'Canada',
    city: 'Toronto',
  },
  {
    email: 'jonathan5@ooland.com',
    name: 'Jonathan5',
    address: 'Sunset Lane',
    phone: 555002004,
    password: '12aaAA##',
    country: 'Spain',
    city: 'Barcelona',
  },
  {
    email: 'jonathan6@ooland.com',
    name: 'Jonathan6',
    address: 'River Street',
    phone: 555002005,
    password: '12aaAA##',
    country: 'France',
    city: 'Paris',
  },
  {
    email: 'jonathan7@ooland.com',
    name: 'Jonathan7',
    address: 'Forest Road',
    phone: 555002006,
    password: '12aaAA##',
    country: 'Germany',
    city: 'Berlin',
  },
  {
    email: 'jonathan8@ooland.com',
    name: 'Jonathan8',
    address: 'Valley Park',
    phone: 555002007,
    password: '12aaAA##',
    country: 'Brazil',
    city: 'Rio de Janeiro',
  },
  {
    email: 'jonathan9@ooland.com',
    name: 'Jonathan9',
    address: 'Desert Sand',
    phone: 555002008,
    password: '12aaAA##',
    country: 'Australia',
    city: 'Sydney',
  },
  {
    email: 'jonathan10@ooland.com',
    name: 'Jonathan10',
    address: 'Island Bay',
    phone: 555002009,
    password: '12aaAA##',
    country: 'Japan',
    city: 'Tokyo',
  },
  {
    email: 'jonathan11@ooland.com',
    name: 'Jonathan11',
    address: 'Alpine Peak',
    phone: 555002010,
    password: '12aaAA##',
    country: 'Switzerland',
    city: 'Zurich',
  },
];
